name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION_STABLE: 1.83.0

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_STABLE }}
          profile: minimal
          override: true
      - name: Install clippy
        run: rustup component add --toolchain 1.83.0-x86_64-unknown-linux-gnu clippy
      - name: Install rustfmt
        run: rustup component add --toolchain 1.83.0-x86_64-unknown-linux-gnu rustfmt
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test --verbose